### ISSUE TITLE
Training New Data

### ISSUE THREAD

**Issue by chnanc001** [Engineering-Course/LIP_JPPNet#19]
Would it be possible to train using a completely new set of data?  Why is it necessary to download a pre-trained model for training?

**Comment by Engineering-Course** [comment]
Yes, you can train a new set of data. The pre-trained model is optional.

**Comment by chnanc001** [comment]
thanks for the response,
would you be able to help me determine what the cause for the following error is?

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LIP_JPPNet-master\train_JPPNet-s2.py", line 333, in <module>
    main()
  File "C:\Users\Administrator\Desktop\LIP_JPPNet-master\train_JPPNet-s2.py", line 287, in main
    summary, loss_value, _ = sess.run([loss_summary, reduced_loss, train_op], feed_dict=feed_dict)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](create_inputs/batch/fifo_queue, Tower_0/gradients/Tower_0/Mean_7_grad/Maximum)]]

Caused by op 'create_inputs/batch', defined at:
  File "C:\Program Files (x86)\pyzo\source\pyzo\pyzokernel\start.py", line 151, in <module>
    __pyzo__.run()
  File "C:\Program Files (x86)\pyzo\source\pyzo\pyzokernel\interpreter.py", line 222, in run
    self.guiApp.run(self.process_commands, self.sleeptime)
  File "C:\Program Files (x86)\pyzo\source\pyzo\pyzokernel\guiintegration.py", line 424, in run
    self._QtGui.real_QApplication.exec_()
  File "C:\Program Files (x86)\pyzo\source\pyzo\pyzokernel\interpreter.py", line 568, in process_commands
    self._process_commands()
  File "C:\Program Files (x86)\pyzo\source\pyzo\pyzokernel\interpreter.py", line 596, in _process_commands
    self.runfile(tmp)
  File "C:\Program Files (x86)\pyzo\source\pyzo\pyzokernel\interpreter.py", line 872, in runfile
    self.execcode(code)
  File "C:\Program Files (x86)\pyzo\source\pyzo\pyzokernel\interpreter.py", line 935, in execcode
    exec(code, self.locals)
  File "C:\Users\Administrator\Desktop\LIP_JPPNet-master\train_JPPNet-s2.py", line 333, in <module>
    main()
  File "C:\Users\Administrator\Desktop\LIP_JPPNet-master\train_JPPNet-s2.py", line 47, in main
    image_batch, label_batch, heatmap_batch = reader.dequeue(BATCH_SIZE)
  File "C:\Users\Administrator\Desktop\LIP_JPPNet-master\utils\lip_reader.py", line 271, in dequeue
    image_batch, label_batch, heatmap_batch = tf.train.batch([self.image, self.label, self.heatmap], num_elements)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\training\input.py", line 988, in batch
    name=name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\training\input.py", line 762, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 483, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 3799, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](create_inputs/batch/fifo_queue, Tower_0/gradients/Tower_0/Mean_7_grad/Maximum)]]

**Comment by zhly0** [comment]
Hi，have you solve the problem？I have the same problem
Thanks！

**Comment by SAHIB-MAJITHIA** [comment]
Hi, you need to create heatmaps from landmarks using dataset/lip/create_heatmap.py. This resolved the error for me.

**Comment by FatimaZulfiqar** [comment]
Hi I am working on person reidentification problem and for that I am trying to create heatmap on market 1501 dataset. Can anybody please guide me how can I do that?
