### ISSUE TITLE
problem while running evaluate_parsing_JPPNet-s2.py on MVC dataset

### ISSUE THREAD

**Issue by rshivansh** [Engineering-Course/LIP_JPPNet#2]
Hi,
I am trying to test your pretrained model on mvc dataset for getting the segmentation results. Wherein i get the following error:
Restored model parameters from model.ckpt-205632
 [*] Load SUCCESS
step 0
./datasets/examples/shirts/1029866-1-MULTIVIEW.jpg
step 100
./datasets/examples/shirts/1125331-1-MULTIVIEW.jpg
2018-04-16 18:30:08.559618: E tensorflow/core/lib/jpeg/jpeg_mem.cc:307] Premature end of JPEG data. Stopped at line 304/560
Traceback (most recent call last):
  File "evaluate_parsing_JPPNet-s2.py", line 160, in <module>
    main()
  File "evaluate_parsing_JPPNet-s2.py", line 144, in main
    parsing_ = sess.run(pred_all)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data or crop window, data size 16384
	 [[Node: create_inputs/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](create_inputs/ReadFile)]]
	 [[Node: create_inputs/concat/_1219 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_586_create_inputs/concat", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'create_inputs/DecodeJpeg', defined at:
  File "evaluate_parsing_JPPNet-s2.py", line 160, in <module>
    main()
  File "evaluate_parsing_JPPNet-s2.py", line 36, in main
    reader = ImageReader(DATA_DIRECTORY, DATA_LIST_PATH, None, False, False, coord)
  File "/home/robolab/ash_data/LIP_JPPNet/utils/image_reader.py", line 150, in __init__
    self.image = read_images_from_disk(self.queue, self.input_size, random_scale, random_mirror)
  File "/home/robolab/ash_data/LIP_JPPNet/utils/image_reader.py", line 113, in read_images_from_disk
    img = tf.image.decode_jpeg(img_contents, channels=3)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 634, in decode_jpeg
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Invalid JPEG data or crop window, data size 16384
	 [[Node: create_inputs/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](create_inputs/ReadFile)]]
	 [[Node: create_inputs/concat/_1219 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_586_create_inputs/concat", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

robolab@robolab:~/ash_data/LIP_JPPNet$ 

I have removed the corrupted jpeg files still the error exists.
Pls help.
Thanks

**Comment by Engineering-Course** [comment]
Make sure that all your input images are jpg format. Otherwise, rewrite the function for reading images.
