### ISSUE TITLE
Cannot run the inference

### ISSUE THREAD

**Issue by yfang1028** [Engineering-Course/LIP_JPPNet#3]
When I run evaluate_pose_JPPNet-s2.py, I got the following error:

Traceback (most recent call last):
  File "evaluate_pose_JPPNet-s2.py", line 168, in <module>
    main()
  File "evaluate_pose_JPPNet-s2.py", line 45, in main
    net_100 = JPPNetModel({'data': image_batch}, is_training=False, n_classes=N_CLASSES)
  File "/Users/yfang/LIP_JPPNet/kaffe/tensorflow/network.py", line 48, in __init__
    self.setup(is_training, n_classes)
  File "/Users/yfang/LIP_JPPNet/utils/model.py", line 18, in setup
    (self.feed('data')
  File "/Users/yfang/LIP_JPPNet/kaffe/tensorflow/network.py", line 78, in feed
    if isinstance(fed_layer, basestring):
NameError: name 'basestring' is not defined

Can you help? Thanks a lot!

**Comment by yfang1028** [comment]
Solved.
Change 'basestring' to 'str'. It seems the code is written in python 2.7. There are other modifications for making it run in python 3.6.

**Comment by Engineering-Course** [comment]
Yes. The code is written in python 2.7

**Comment by yfang1028** [comment]
@achalshah20 Yes, it works for me in python 3.6 now. There are not many changes needed.

**Comment by achalshah20** [comment]
@Engineering-Course I did a few changes in parsing evaluation to make it work in both python3.6 and python2.7. #4

**Comment by Engineering-Course** [comment]
@achalshah20  Thanks!
