### ISSUE TITLE
cannot run code,need your help!

### ISSUE THREAD

**Issue by ChenDRAG** [Engineering-Course/LIP_JPPNet#37]
hi there.
i download the code in ubuntu and run evaluate_pose_JPPNet-s2.py
however it gives me the following message.
could you please tell me how to fix it?

chy@chy:~/Desktop/LIP_JPPNet-master$ python3 evaluate_pose_JPPNet-s2.py
WARNING:tensorflow:From /home/chy/.local/lib/python3.5/site-packages/tensorflow/python/training/input.py:187: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/chy/.local/lib/python3.5/site-packages/tensorflow/python/training/input.py:187: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From evaluate_pose_JPPNet-s2.py:112: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
2018-12-10 16:23:21.554299: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
 [!] Load failed...
WARNING:tensorflow:From evaluate_pose_JPPNet-s2.py:135: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2018-12-10 16:23:36.287999: W tensorflow/core/framework/allocator.cc:113] Allocation of 235929600 exceeds 10% of system memory.
2018-12-10 16:23:36.296293: W tensorflow/core/framework/allocator.cc:113] Allocation of 191102976 exceeds 10% of system memory.
Traceback (most recent call last):
  File "evaluate_pose_JPPNet-s2.py", line 168, in <module>
    main()
  File "evaluate_pose_JPPNet-s2.py", line 141, in main
    save_lip_images(image_list[step], predict_, OUTPUT_DIR)
  File "evaluate_pose_JPPNet-s2.py", line 158, in save_lip_images
    for p in xrange(image.shape[2]):
NameError: name 'xrange' is not defined

**Comment by Engineering-Course** [comment]
The code is written in python2.
You should change some features for python3, such as xrange -> range.
