### ISSUE TITLE
some problems in  evaluate_parsing_JPPNet-s2.py,,maybe bugs?

### ISSUE THREAD

**Issue by ChenDRAG** [Engineering-Course/LIP_JPPNet#39]
when i first run the evaluate_parsing_JPPNet-s2.py,it gives good results,
but when i switch to another 6 pictures in the same format.it gives me the 
following error message. i wonder why  this happens? 

Traceback (most recent call last):
  File "evaluate_parsing_JPPNet-s2.py", line 160, in <module>
    main()
  File "evaluate_parsing_JPPNet-s2.py", line 144, in main
    parsing_ = sess.run(pred_all)
  File "/home/chy/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/chy/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/chy/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/chy/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: datasets/examples
	 [[Node: create_inputs/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/input_producer/Gather)]]

Caused by op u'create_inputs/ReadFile', defined at:
  File "evaluate_parsing_JPPNet-s2.py", line 160, in <module>
    main()
  File "evaluate_parsing_JPPNet-s2.py", line 36, in main
    reader = ImageReader(DATA_DIRECTORY, DATA_LIST_PATH, None, False, False, coord)
  File "/home/chy/Desktop/LIP_JPPNet-master/utils/image_reader.py", line 147, in __init__
    self.image = read_images_from_disk(self.queue, self.input_size, random_scale, random_mirror)
  File "/home/chy/Desktop/LIP_JPPNet-master/utils/image_reader.py", line 111, in read_images_from_disk
    img_contents = tf.read_file(input_queue[0])
  File "/home/chy/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 223, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/home/chy/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/chy/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/chy/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): datasets/examples
	 [[Node: create_inputs/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/input_producer/Gather)]]

**Comment by Engineering-Course** [comment]
Do you change the val.txt in example/list?

**Comment by ChenDRAG** [comment]
yes? but when i first try ,it seems that changing val.txt in example/list is ok and it gives me reasonable results?
this is my present val.txt

```
/images/rgb540720/24.jpg
/images/rgb540720/25.jpg
/images/rgb540720/26.jpg
/images/rgb540720/27.jpg
/images/rgb540720/29.jpg
```

**Comment by Engineering-Course** [comment]
and then your images should be put in /images/rbg540720

**Comment by ChenDRAG** [comment]
problem solved .I'm being stupid,Thanks a lot.
